### ISSUE TITLE
Need to add jsx-equals-spacing rule

### ISSUE THREAD

**Issue by Danno040** [SocialEngine/eslint-config#1]
Currently, the linter isn't enforcing spacing around JSX properties. For example, all of these are fair game:

``` jsx
<div foo={'bar'} />
<div foo ={'bar'} />
<div foo= {'bar'} />
<div foo = {'bar'} />
```

I propose we totally disallow spaces, so only the first example is valid.

We just need to add this line:

``` json
'react/jsx-equals-spacing': [2, 'never'],
```

to rules/react.js.

**Comment by smazurov** [comment]
agreed.

**Comment by Danno040** [comment]
Done. Should I retag as `1.1.0` or `1.1.1`?

**Comment by smazurov** [comment]
you can retag, update `package.json` to `1.1.0` as part of that tagged commit
