### ISSUE TITLE
Add object-curly-spacing rule

### ISSUE THREAD

**Issue by Danno040** [SocialEngine/eslint-config#2]
It has become clear that we prefer to have spaces around imports, and are willing to accept spaces around the curly brackets for objects.

We should add [object-curly-spacing](http://eslint.org/docs/rules/object-curly-spacing) to rules/style.js:

```
'object-curly-spacing': [2, 'always']
```

**Comment by smazurov** [comment]
go for it, tag it as `1.1.0`, i can push to npm
